### ISSUE TITLE
[1.19.1---1.19.2] Game crashing instead of normal behaviour when using a totem of dying and undying toghether

### ISSUE THREAD

**Issue by ZeroKun265** [ZeroKun265/Totem_Of_Dying#3]
Everything else works perfectly but the game crashes when using 2 different totems toghether
Version 1.0.1 therefore isn't compatible with minecraft 1.19.2 and 1.19.2

```
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2022-10-10 09:47:56
Description: Exception in server tick loop

java.lang.NoSuchFieldError: field_11735
	at net.minecraft.class_1657.handler$zjc000$damageTotemOfDying(class_1657.java:3442)
	at net.minecraft.class_1657.method_5643(class_1657.java)
	at net.minecraft.class_3222.method_5643(class_3222.java:713)
	at net.minecraft.class_1309.method_5747(class_1309.java:1553)
	at net.minecraft.class_1657.method_5747(class_1657.java:1746)
	at net.minecraft.class_2248.method_9554(class_2248.java:469)
	at net.minecraft.class_1297.method_5623(class_1297.java:1175)
	at net.minecraft.class_1309.method_5623(class_1309.java:325)
	at net.minecraft.class_3222.method_14207(class_3222.java:1009)
	at net.minecraft.class_3244.method_12063(class_3244.java:1002)
	at net.minecraft.class_2828.method_12272(class_2828.java:114)
	at net.minecraft.class_2828$class_2829.method_11054(class_2828.java:42)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:157)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159)
	at net.minecraft.class_1255.method_16075(class_1255.java:131)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752)
	at net.minecraft.class_1255.method_18857(class_1255.java:140)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.19.1
	Minecraft Version ID: 1.19.1
	Operating System: Linux (amd64) version 5.19.13-arch1-1
	Java Version: 17.0.4.1, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 991772160 bytes (945 MiB) / 2157969408 bytes (2058 MiB) up to 3221225472 bytes (3072 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx
	Identifier: AuthenticAMD Family 23 Model 24 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Picasso/Raven 2 [Radeon Vega Series / Radeon Vega Mobile Series]
	Graphics card #0 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #0 VRAM (MB): 258.00
	Graphics card #0 deviceId: 0x15d8
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 11946.37
	Virtual memory used (MB): 5399.05
	Swap memory total (MB): 9011.20
	Swap memory used (MB): 509.48
	JVM Flags: 2 total; -Xms307m -Xmx3072m
	Fabric Mods: 
		fabric: Fabric API 0.58.5+1.19.1
			fabric-api-base: Fabric API Base 0.4.9+e62f51a395
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f4095
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.15+d5533c0195
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f4095
			fabric-command-api-v1: Fabric Command API (v1) 1.2.9+f71b366f95
			fabric-command-api-v2: Fabric Command API (v2) 2.1.5+0c17ea9695
			fabric-commands-v0: Fabric Commands (v0) 0.2.26+df3654b395
			fabric-containers-v0: Fabric Containers (v0) 0.1.31+df3654b395
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.1+07df213e95
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d2495
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4a95
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.5+a680b9b495
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.28+a6d2f78595
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f4095
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f4095
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.26+df3654b395
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+1899036195
			fabric-item-api-v1: Fabric Item API (v1) 1.5.5+35a03c4395
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.26+9ff28f4095
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.18+9ff28f4095
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b395
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc73895
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.1+03a4e56895
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.4+9e7660c695
			fabric-message-api-v1: Fabric Message API (v1) 5.0.1+4e0178f495
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.11+33fbc73895
			fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f4095
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.1+3082331495
			fabric-networking-v0: Fabric Networking (v0) 0.3.18+df3654b395
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.8+9ff28f4095
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553a95
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.21+23c4cfef95
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f4095
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.10+5187d39f95
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b395
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f4095
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f4095
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b395
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f4095
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a395
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.6+5f1a85e095
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.24+f05effaf95
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.10+9ff28f4095
			fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f4095
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.9+e62f51a395
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c695
		fabricloader: Fabric Loader 0.14.9
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.19.1
		totem_of_dying: Totem Of Dying 1.0.1
	Server Running: true
	Player Count: 1 / 8; [class_3222['ZeroKun265'/202, l='ServerLevel[New World]', x=8.50, y=74.00, z=3.50]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Experimental
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: 1.19.1
```

**Comment by ZeroKun265** [comment]
Fixed in commit 908944c3fdd9bf03a8cd0b07452af87940326de1 
The issue was with a change in the chat system made from minecraft version 1.19.1
